name: Auto Convert Rule

on:
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间凌晨自动执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run convert script
        run: python3 convert.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update smartdns rule"
          git push
